#Node.js Image
FROM node:20-alpine

# Seting a working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy rest of the backend
COPY . .

# Expose port
EXPOSE 3001

# Start server
CMD ["node", "server.js"]
